name: Deploy Application Docker Image to EC2

on:
  push:
    branches: [ main ]

jobs:

# ================= CI =================
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # create repo if not exists (important for first deploy)
      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPO }} \
          || aws ecr create-repository --repository-name ${{ secrets.ECR_REPO }}

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


# ================= CD =================
  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted   # your EC2 runner

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # stop old container if exists
      - name: Stop old container
        run: |
          docker stop vehicle_app || true
          docker rm vehicle_app || true

      # pull latest image
      - name: Pull latest image
        run: |
          docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}:latest

      # run container
      - name: Run Docker container
        run: |
          docker run -d \
          --name vehicle_app \
          -p 5000:5000 \
          -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
          -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
          ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}:latest
